Correct error messages

diff --git a/.github/workflows/changelog-verification.yml b/.github/workflows/changelog-verification.yml
--- a/.github/workflows/changelog-verification.yml
+++ b/.github/workflows/changelog-verification.yml
@@ -1,5 +1,8 @@
 name: Changelog verification
 
+permissions:
+  id-token: write
+
 on:
   pull_request:
     types: [ opened, synchronize, reopened, labeled, unlabeled ]
@@ -24,17 +27,17 @@ jobs:
       - name: Check for new changelog entry
         if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
         run: |
-          git fetch origin ${{ github.base_ref }} --depth 1 && \
-          git diff remotes/origin/${{ github.base_ref }} --name-only | grep -P "\.changes/[0-9a-f-]+\.json"
+          git fetch origin ${{ github.base_ref }} --depth 1
+          if ! git diff remotes/origin/${{ github.base_ref }} --name-only | grep -P "\.changes/[0-9a-f-]+\.json"; then
+            echo "::error ::No new/updated changelog entry found in /.changes directory. Please either:"
+            echo "::error ::* Add a changelog entry (see CONTRIBUTING.md for instructions) –or–"
+            echo "::error ::* Add the 'no-changelog' label to this PR (in rare cases not warranting a changelog entry)"
+            exit 1
+          fi
 
       - name: Verify all changelogs
         run: |
-          kat changelog ls
-
-      - name: Error message
-        if: ${{ failure() }}
-        run: |
-          echo "::error ::No new/updated changelog entry found in /.changes directory. Please either:"
-          echo "::error ::* Add a changelog entry (see CONTRIBUTING.md for instructions) –or–"
-          echo "::error ::* Add the 'no-changelog' label to this PR (in rare cases not warranting a changelog entry)"
-          exit 1
+          if ! kat changelog ls; then
+            echo "::error ::Changelog verification failed. Please check the format of your changelog entry."
+            exit 1
+          fi
