proper error message & temp test

diff --git a/.github/workflows/release-readiness.yml b/.github/workflows/release-readiness.yml
--- a/.github/workflows/release-readiness.yml
+++ b/.github/workflows/release-readiness.yml
@@ -17,8 +17,11 @@ jobs:
       - name: Configure Gradle
         uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
 
-      - name: Configure error message
-        run: echo "ERROR_MESSAGE=WARNING aws-crt-kotlin release and version bump might be required before merging" >> $GITHUB_ENV
-
       - name: Build smithy-kotlin
-        run: ./gradlew test jvmTest || { echo "$ERROR_MESSAGE"; exit 1; }
+        run: ./gradlew test jvmTest
+
+      - name: Emit error message
+        if: ${{ failure() }}
+        run: |
+          echo "::error ::Build failed. Did you forget to release aws-crt-kotlin and bump the dependency version?"
+          exit 1
